enabled: true
targets:
  - name: Memorial Day Balboa
    teesheet_id: 1470
    booking_class: 929
dates:
  start: '2026-05-25'
  end: '2026-05-25'
filter:
  holes: 18
  min_players: 1
  max_green_fee: null
  windows:
    - start: 08:00
      end: 04:00
      weekdays:
        - mon
