enabled: true
targets:
  - name: Torrey Pines North
    teesheet_id: 1468
    booking_class: 51735
  - name: Torrey Pines South
    teesheet_id: 1487
    booking_class: 51735
dates:
  start: today
  end: today+90
filter:
  holes: 18
  min_players: 4
  windows:
    - start: 07:00
      end: 11:00
      weekdays:
        - sat
        - sun
